# Generated by Django 3.0.7 on 2020-06-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=265)),
                ('Price', models.CharField(max_length=1024)),
                ('Stock', models.DateTimeField(verbose_name='Released on:')),
                ('Color', models.CharField(max_length=1024)),
                ('Picture_link', models.CharField(max_length=20)),
                ('Rating', models.IntegerField()),
                ('Release_date', models.IntegerField()),
                ('Offers', models.CharField(max_length=255)),
                ('Company', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Wishlist', models.IntegerField()),
                ('Bought', models.IntegerField()),
            ],
        ),
    ]
