# Generated by Django 3.0.7 on 2020-06-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Details',
            field=models.CharField(default='None', max_length=1236),
            preserve_default=False,
        ),
    ]
