# Generated by Django 3.0.7 on 2020-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
