# Generated by Django 3.0.7 on 2020-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200625_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Picture_link',
            field=models.CharField(max_length=500),
        ),
    ]
