# Generated by Django 3.0.7 on 2020-06-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200625_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Rating',
            field=models.FloatField(),
        ),
    ]
