# Generated by Django 3.0.7 on 2020-06-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200625_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Release_date',
            field=models.DateTimeField(verbose_name='Released on:'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Stock',
            field=models.IntegerField(),
        ),
    ]
