# Generated by Django 3.0.7 on 2020-07-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200625_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Details',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Bought',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Wishlist',
        ),
    ]
