# Generated by Django 3.0.7 on 2020-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_products_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(max_length=99999999999999),
        ),
    ]
